### ISSUE TITLE
[Azure DevOps Server] Unexpected token ﻿ in JSON at position 0

### ISSUE THREAD

**Issue by Loupeznik** [Loupeznik/ADOConfigTransformTask#2]
Using Azure DevOps Server classic pipelines, the following error occures:

```
Starting: Transform appsettings.json buildVersion
==============================================================================
Task         : Configuration Transformation
Description  : Configuration transformation task for Azure DevOps
Version      : 1.2.5
Author       : Dominik Zarsky
Help         : 
==============================================================================
##[error]An error has occured during transformation - Unexpected token ﻿ in JSON at position 0
Finishing: Transform appsettings.json buildVersion
```

This does not happen in similarly structured file on Azure DevOps Services using YAML pipelines.

The input yaml was:

```
steps:
- task: DominikZarsky.config-transform-task.config-transform-task.ConfigurationTransformation@1
  displayName: 'Transform appsettings.json buildVersion'
  inputs:
    fileType: json
    targetPath: '$(Build.SourcesDirectory)\src\Example.Api\appsettings.json'
    transformations: |
     {
       "InsuranceConfig.BuildVersion": "$(Build.BuildNumber)"
     }
```
