### ISSUE TITLE
[ALL] Flat file transformation does not create keys if they don't exist in the target file

### ISSUE THREAD

**Issue by Loupeznik** [Loupeznik/ADOConfigTransformTask#4]
The `AUTH0_*` keys from the following example are not created if not present in the `.env` file:

```yaml
steps:
- task: ConfigurationTransformation@1
  inputs:
    fileType: "flat"
    targetPath: "$(DEPLOY_DIRECTORY)/.env"
    transformations: |
      {
        "MAIL_MAILER": "smtp",
        "MAIL_HOST": "smtp.seznam.cz",
        "MAIL_PORT": 25,
        "MAIL_USERNAME": "$(SMTP_USERNAME)",
        "MAIL_PASSWORD": "$(SMTP_PASSWORD)",
        "MAIL_ENCRYPTION": null,
        "MAIL_FROM_NAME": "Laravel app",
        "MAIL_FROM_ADDRESS": "$(SMTP_USERNAME)",
        "EMAILS_ENABLED": $(EMAILS_ENABLED),
        "AUTH0_DOMAIN": "$(AUTH0_DOMAIN)",
        "AUTH0_CLIENT_ID": "$(AUTH0_CLIENT_ID)",
        "AUTH0_CLIENT_SECRET": "$(AUTH0_CLIENT_SECRET)",
        "AUTH0_AUDIENCE": "https://github.com/auth0/laravel-auth0"
      }
```

Add creating these keys as part of the transformation
